all: puzzle_1 puzzle_2

puzzle_1:
	g++ puzzle_1.cpp rangedata.cpp inputdata.cpp utils.cpp -o puzzle_1.out
puzzle_2:
	g++ puzzle_2.cpp rangedata.cpp inputdata.cpp utils.cpp -o puzzle_2.out

clean:
	rm -f puzzle_1.out puzzle_2.out
